 # Artificial Intelligence Technology and Application

 ## Deep Learning Lab Guide - Student Version

 # 1 MindSpore Basics

 ## 1.1 Introduction

 This exercise introduces the tensor data structure of MindSpore. By performing a series of operations on tensors, you can understand the basic syntax of MindSpore.

 ## 1.2 Procedure

 ### 1.2.1 Introduction to Tensors

 #### 1.2.1.1 Creating a Tensor

In [1]:
import numpy as np

# Note: The code below requires `mindspore` to be installed.
# Using try-except block to allow running the file even if mindspore is not installed locally yet.
try:
    import mindspore
    from mindspore import Tensor
    from mindspore import dtype
    from mindspore import ops
    import mindspore.nn as nn
    from mindspore import Model

    # Use an array to create a tensor
    x = Tensor(np.array([[1, 2], [3, 4]]), dtype.int32)
    print("Array Tensor:\n", x)

    # Use numbers to create tensors
    y = Tensor(1.0, dtype.float32)
    z = Tensor(2, dtype.int32)
    print("\nNumber Tensors:\n", y, "\n", z)

    # Use Boolean to create a tensor
    m = Tensor(True, dtype.bool_)
    print("\nBoolean Tensor:\n", m)

    # Use a list to create a tensor
    l_tensor = Tensor([4.0, 5.0, 6.0], dtype.float64)
    print("\nList Tensor:\n", l_tensor)

    # Inherit attributes using OnesLike
    oneslike = ops.OnesLike()
    x_int = Tensor(np.array([[0, 1], [2, 1]]).astype(np.int32))
    output_ones_like = oneslike(x_int)
    print("\nOnesLike output:\n", output_ones_like)

    # Output constant tensor value
    shape = (2, 2)
    ones = ops.Ones()
    output_ones = ones(shape, dtype.float32)
    print("\nConstant Ones output:\n", output_ones)

    zeros = ops.Zeros()
    output_zeros = zeros(shape, dtype.float32)
    print("\nConstant Zeros output:\n", output_zeros)

except ImportError:
    print("MindSpore is not installed. Please install it using `pip install mindspore`.")



Array Tensor:
 [[1 2]
 [3 4]]

Number Tensors:
 1.0 
 2

Boolean Tensor:
 True

List Tensor:
 [4. 5. 6.]

OnesLike output:
 [[1 1]
 [1 1]]

Constant Ones output:
 [[1. 1.]
 [1. 1.]]

Constant Zeros output:
 [[0. 0.]
 [0. 0.]]


 #### 1.2.1.2 Tensor Attributes & 1.2.1.3 Tensor Methods

In [2]:
try:
    x_attr = Tensor(np.array([[1, 2], [3, 4]]), dtype.int32)
    print("\nShape:", x_attr.shape)
    print("Data type:", x_attr.dtype)
    print("Dimension:", x_attr.ndim)
    print("Size:", x_attr.size)

    y_bool = Tensor(np.array([[True, True], [False, False]]), dtype.bool_)
    print("\nTensor format:\n", y_bool)
    print("\nNumPy format (asnumpy):\n", y_bool.asnumpy())
except NameError:
    pass



Shape: (2, 2)
Data type: Int32
Dimension: 2
Size: 4

Tensor format:
 [[ True  True]
 [False False]]

NumPy format (asnumpy):
 [[ True  True]
 [False False]]


 #### 1.2.1.4 Tensor Operations

In [3]:
try:
    tensor_op = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
    print("\nFirst row:", tensor_op[0])
    print("First column:", tensor_op[:, 0])
    print("Last column:", tensor_op[..., -1])

    data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
    data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
    stack_op = ops.Stack()
    output_stack = stack_op([data1, data2])
    print("\nStacked tensors:\n", output_stack)

except NameError:
    pass



First row: [0. 1.]
First column: [0. 2.]
Last column: [1. 3.]

Stacked tensors:
 [[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


 ### 1.2.2 Loading a Dataset

 #### Customize a dataset using GeneratorDataset

In [4]:
import mindspore.dataset as ds

np.random.seed(58)

class DatasetGenerator:
    def __init__(self):
        self.data = np.random.sample((5, 2)).astype(np.float32)
        self.label = np.random.sample((5, 1)).astype(np.float32)

    def __getitem__(self, index):
        return self.data[index], self.label[index]

    def __len__(self):
        return len(self.data)

try:
    dataset_gen = DatasetGenerator()
    dataset = ds.GeneratorDataset(dataset_gen, column_names=["data", "label"])
    
    # Shuffle and Batch
    ds.config.set_seed(58)
    dataset = dataset.shuffle(buffer_size=5)
    dataset = dataset.batch(batch_size=2)
    
    print("\nGeneratorDataset Output After Batching:")
    for data in dataset.create_dict_iterator():
        print("Data:\n", data["data"].asnumpy())
        print("Label:\n", data["label"].asnumpy())

except NameError:
    pass
except Exception as e:
    print(f"Dataset error: {e}")



GeneratorDataset Output After Batching:
Data:
 [[0.49606034 0.07562207]
 [0.5717616  0.28963402]]
Label:
 [[0.3806818 ]
 [0.16271621]]
Data:
 [[0.30880445 0.37487617]
 [0.8158567  0.9688347 ]]
Label:
 [[0.54738766]
 [0.77994066]]
Data:
 [[0.36510557 0.4512059 ]]
Label:
 [[0.78888124]]


 ### 1.2.3 Building the Network

In [5]:
try:
    # Fully connected layer
    input_a = Tensor(np.array([[1, 1, 1], [2, 2, 2]]), mindspore.float32)
    net_dense = nn.Dense(in_channels=3, out_channels=3, weight_init='ones')
    print("\nDense Layer Output:\n", net_dense(input_a))

    # Convolutional layer
    conv2d = nn.Conv2d(1, 6, 5, has_bias=False, weight_init='normal', pad_mode='valid')
    input_x_conv = Tensor(np.ones([1, 1, 32, 32]), mindspore.float32)
    print("\nConv2d Shape:", conv2d(input_x_conv).shape)

    # ReLU layer
    relu = nn.ReLU()
    input_x_relu = Tensor(np.array([-1, 2, -3, 2, -1]), mindspore.float32)
    print("\nReLU Output:", relu(input_x_relu))

    # Max Pooling
    max_pool2d = nn.MaxPool2d(kernel_size=2, stride=2)
    input_x_pool = Tensor(np.ones([1, 6, 28, 28]), mindspore.float32)
    print("\nMaxPool2d Shape:", max_pool2d(input_x_pool).shape)

    # Flatten
    flatten = nn.Flatten()
    input_x_flat = Tensor(np.ones([1, 16, 5, 5]), mindspore.float32)
    print("\nFlatten Shape:", flatten(input_x_flat).shape)

    # Define LeNet5 Model Class Structure
    class LeNet5(nn.Cell):
        def __init__(self):
            super(LeNet5, self).__init__()
            self.conv1 = nn.Conv2d(1, 6, 5, pad_mode='valid')
            self.conv2 = nn.Conv2d(6, 16, 5, pad_mode='valid')
            self.flatten = nn.Flatten()
            self.fc1 = nn.Dense(16 * 4 * 4, 120)
            self.fc2 = nn.Dense(120, 84)
            self.fc3 = nn.Dense(84, 10)
            self.relu = nn.ReLU()
            self.max_pool2d = nn.MaxPool2d(kernel_size=2, stride=2)

        def construct(self, x):
            x = self.max_pool2d(self.relu(self.conv1(x)))
            x = self.max_pool2d(self.relu(self.conv2(x)))
            x = self.flatten(x)
            x = self.relu(self.fc1(x))
            x = self.relu(self.fc2(x))
            x = self.fc3(x)
            return x

    network = LeNet5()
    print("\nLeNet5 parameters:")
    for name, param in network.parameters_and_names():
        print(f"Name: {name}, Shape: {param.shape}")

except NameError:
    pass



Dense Layer Output:
 [[3.1284747 3.0900786 3.5357811]
 [6.1284747 6.0900784 6.5357814]]

Conv2d Shape: (1, 6, 28, 28)

ReLU Output: [0. 2. 0. 2. 0.]

MaxPool2d Shape: (1, 6, 14, 14)

Flatten Shape: (1, 400)

LeNet5 parameters:
Name: conv1.weight, Shape: (6, 1, 5, 5)
Name: conv2.weight, Shape: (16, 6, 5, 5)
Name: fc1.weight, Shape: (120, 256)
Name: fc1.bias, Shape: (120,)
Name: fc2.weight, Shape: (84, 120)
Name: fc2.bias, Shape: (84,)
Name: fc3.weight, Shape: (10, 84)
Name: fc3.bias, Shape: (10,)


 ### 1.2.4 Training and Validating a Model

In [6]:
try:
    # L1 Loss
    loss_l1 = nn.L1Loss()
    output_data = Tensor(np.array([[1, 2, 3], [2, 3, 4]]).astype(np.float32))
    target_data = Tensor(np.array([[0, 2, 5], [3, 1, 1]]).astype(np.float32))
    print("\nL1 Loss:", loss_l1(output_data, target_data))

    # Optimizer (Momentum) & Model definition
    loss_fn = nn.SoftmaxCrossEntropyWithLogits(sparse=True, reduction='mean')
    optim = nn.Momentum(params=network.trainable_params(), learning_rate=0.1, momentum=0.9)
    
    model = Model(network=network, loss_fn=loss_fn, optimizer=optim, metrics={'accuracy'})
    print("\nModel Compiled Successfully.")

    # Saving Model example (Commented to avoid auto execution issues)
    # mindspore.save_checkpoint(network, "./MyNet.ckpt")

except NameError:
    pass



L1 Loss: 1.5

Model Compiled Successfully.


 ### 1.2.6 Automatic Differentiation

In [7]:
try:
    from mindspore import Parameter
    
    class NetWithDeriv(nn.Cell):
        def __init__(self):
            super(NetWithDeriv, self).__init__()
            self.z = Parameter(Tensor(np.array([[1.0, 1.0], [1.0, 1.0]], np.float32)), name='z')
            
        def construct(self, x, y):
            return self.z * x * y

    net_deriv = NetWithDeriv()
    grad_op = ops.GradOperation(get_all=True)
    
    x_input = Tensor(np.array([[1.0, 2.0], [3.0, 4.0]], np.float32))
    y_input = Tensor(np.array([[1.0, 1.0], [1.0, 1.0]], np.float32))
    
    output_grad = grad_op(net_deriv)(x_input, y_input)
    print("\nFirst-order derivative of inputs w.r.t loss:")
    print("grad x:\n", output_grad[0])
    print("grad y:\n", output_grad[1])

except NameError:
    pass



First-order derivative of inputs w.r.t loss:
grad x:
 [[1. 1.]
 [1. 1.]]
grad y:
 [[1. 2.]
 [3. 4.]]
